/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternetOfThingRouteImport } from './routes/internet-of-thing'
import { Route as IntegrationAsAServiceRouteImport } from './routes/integration-as-a-service'
import { Route as AutomationRouteImport } from './routes/automation'

const TermsLazyRouteImport = createFileRoute('/terms')()
const TechnologyAndHighGrowthCompaniesLazyRouteImport = createFileRoute(
  '/technology-and-high-growth-companies',
)()
const SolutionsLazyRouteImport = createFileRoute('/solutions')()
const SoftwareDevelopmentLazyRouteImport = createFileRoute(
  '/software-development',
)()
const ServicesLazyRouteImport = createFileRoute('/services')()
const RetailAndEcommerceLazyRouteImport = createFileRoute(
  '/retail-and-ecommerce',
)()
const RealStateLazyRouteImport = createFileRoute('/real-state')()
const ProductsLazyRouteImport = createFileRoute('/products')()
const PrivacyLazyRouteImport = createFileRoute('/privacy')()
const IndustriesLazyRouteImport = createFileRoute('/industries')()
const HybridCloudLazyRouteImport = createFileRoute('/hybrid-cloud')()
const FinancialServicesAndFintechLazyRouteImport = createFileRoute(
  '/financial-services-and-fintech',
)()
const ContactUsLazyRouteImport = createFileRoute('/contact-us')()
const ConstructionLazyRouteImport = createFileRoute('/construction')()
const CloudServiceLazyRouteImport = createFileRoute('/cloud-service')()
const BusinessOutcomesLazyRouteImport = createFileRoute('/business-outcomes')()
const AboutUsLazyRouteImport = createFileRoute('/about-us')()
const IndexLazyRouteImport = createFileRoute('/')()

const TermsLazyRoute = TermsLazyRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const TechnologyAndHighGrowthCompaniesLazyRoute =
  TechnologyAndHighGrowthCompaniesLazyRouteImport.update({
    id: '/technology-and-high-growth-companies',
    path: '/technology-and-high-growth-companies',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/technology-and-high-growth-companies.lazy').then(
      (d) => d.Route,
    ),
  )
const SolutionsLazyRoute = SolutionsLazyRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/solutions.lazy').then((d) => d.Route))
const SoftwareDevelopmentLazyRoute = SoftwareDevelopmentLazyRouteImport.update({
  id: '/software-development',
  path: '/software-development',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/software-development.lazy').then((d) => d.Route),
)
const ServicesLazyRoute = ServicesLazyRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/services.lazy').then((d) => d.Route))
const RetailAndEcommerceLazyRoute = RetailAndEcommerceLazyRouteImport.update({
  id: '/retail-and-ecommerce',
  path: '/retail-and-ecommerce',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/retail-and-ecommerce.lazy').then((d) => d.Route),
)
const RealStateLazyRoute = RealStateLazyRouteImport.update({
  id: '/real-state',
  path: '/real-state',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/real-state.lazy').then((d) => d.Route))
const ProductsLazyRoute = ProductsLazyRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))
const PrivacyLazyRoute = PrivacyLazyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const IndustriesLazyRoute = IndustriesLazyRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/industries.lazy').then((d) => d.Route))
const HybridCloudLazyRoute = HybridCloudLazyRouteImport.update({
  id: '/hybrid-cloud',
  path: '/hybrid-cloud',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/hybrid-cloud.lazy').then((d) => d.Route))
const FinancialServicesAndFintechLazyRoute =
  FinancialServicesAndFintechLazyRouteImport.update({
    id: '/financial-services-and-fintech',
    path: '/financial-services-and-fintech',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/financial-services-and-fintech.lazy').then((d) => d.Route),
  )
const ContactUsLazyRoute = ContactUsLazyRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact-us.lazy').then((d) => d.Route))
const ConstructionLazyRoute = ConstructionLazyRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/construction.lazy').then((d) => d.Route))
const CloudServiceLazyRoute = CloudServiceLazyRouteImport.update({
  id: '/cloud-service',
  path: '/cloud-service',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cloud-service.lazy').then((d) => d.Route))
const BusinessOutcomesLazyRoute = BusinessOutcomesLazyRouteImport.update({
  id: '/business-outcomes',
  path: '/business-outcomes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/business-outcomes.lazy').then((d) => d.Route),
)
const AboutUsLazyRoute = AboutUsLazyRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about-us.lazy').then((d) => d.Route))
const InternetOfThingRoute = InternetOfThingRouteImport.update({
  id: '/internet-of-thing',
  path: '/internet-of-thing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationAsAServiceRoute = IntegrationAsAServiceRouteImport.update({
  id: '/integration-as-a-service',
  path: '/integration-as-a-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/automation': typeof AutomationRoute
  '/integration-as-a-service': typeof IntegrationAsAServiceRoute
  '/internet-of-thing': typeof InternetOfThingRoute
  '/about-us': typeof AboutUsLazyRoute
  '/business-outcomes': typeof BusinessOutcomesLazyRoute
  '/cloud-service': typeof CloudServiceLazyRoute
  '/construction': typeof ConstructionLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/financial-services-and-fintech': typeof FinancialServicesAndFintechLazyRoute
  '/hybrid-cloud': typeof HybridCloudLazyRoute
  '/industries': typeof IndustriesLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/products': typeof ProductsLazyRoute
  '/real-state': typeof RealStateLazyRoute
  '/retail-and-ecommerce': typeof RetailAndEcommerceLazyRoute
  '/services': typeof ServicesLazyRoute
  '/software-development': typeof SoftwareDevelopmentLazyRoute
  '/solutions': typeof SolutionsLazyRoute
  '/technology-and-high-growth-companies': typeof TechnologyAndHighGrowthCompaniesLazyRoute
  '/terms': typeof TermsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/automation': typeof AutomationRoute
  '/integration-as-a-service': typeof IntegrationAsAServiceRoute
  '/internet-of-thing': typeof InternetOfThingRoute
  '/about-us': typeof AboutUsLazyRoute
  '/business-outcomes': typeof BusinessOutcomesLazyRoute
  '/cloud-service': typeof CloudServiceLazyRoute
  '/construction': typeof ConstructionLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/financial-services-and-fintech': typeof FinancialServicesAndFintechLazyRoute
  '/hybrid-cloud': typeof HybridCloudLazyRoute
  '/industries': typeof IndustriesLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/products': typeof ProductsLazyRoute
  '/real-state': typeof RealStateLazyRoute
  '/retail-and-ecommerce': typeof RetailAndEcommerceLazyRoute
  '/services': typeof ServicesLazyRoute
  '/software-development': typeof SoftwareDevelopmentLazyRoute
  '/solutions': typeof SolutionsLazyRoute
  '/technology-and-high-growth-companies': typeof TechnologyAndHighGrowthCompaniesLazyRoute
  '/terms': typeof TermsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/automation': typeof AutomationRoute
  '/integration-as-a-service': typeof IntegrationAsAServiceRoute
  '/internet-of-thing': typeof InternetOfThingRoute
  '/about-us': typeof AboutUsLazyRoute
  '/business-outcomes': typeof BusinessOutcomesLazyRoute
  '/cloud-service': typeof CloudServiceLazyRoute
  '/construction': typeof ConstructionLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/financial-services-and-fintech': typeof FinancialServicesAndFintechLazyRoute
  '/hybrid-cloud': typeof HybridCloudLazyRoute
  '/industries': typeof IndustriesLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/products': typeof ProductsLazyRoute
  '/real-state': typeof RealStateLazyRoute
  '/retail-and-ecommerce': typeof RetailAndEcommerceLazyRoute
  '/services': typeof ServicesLazyRoute
  '/software-development': typeof SoftwareDevelopmentLazyRoute
  '/solutions': typeof SolutionsLazyRoute
  '/technology-and-high-growth-companies': typeof TechnologyAndHighGrowthCompaniesLazyRoute
  '/terms': typeof TermsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/integration-as-a-service'
    | '/internet-of-thing'
    | '/about-us'
    | '/business-outcomes'
    | '/cloud-service'
    | '/construction'
    | '/contact-us'
    | '/financial-services-and-fintech'
    | '/hybrid-cloud'
    | '/industries'
    | '/privacy'
    | '/products'
    | '/real-state'
    | '/retail-and-ecommerce'
    | '/services'
    | '/software-development'
    | '/solutions'
    | '/technology-and-high-growth-companies'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/integration-as-a-service'
    | '/internet-of-thing'
    | '/about-us'
    | '/business-outcomes'
    | '/cloud-service'
    | '/construction'
    | '/contact-us'
    | '/financial-services-and-fintech'
    | '/hybrid-cloud'
    | '/industries'
    | '/privacy'
    | '/products'
    | '/real-state'
    | '/retail-and-ecommerce'
    | '/services'
    | '/software-development'
    | '/solutions'
    | '/technology-and-high-growth-companies'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/integration-as-a-service'
    | '/internet-of-thing'
    | '/about-us'
    | '/business-outcomes'
    | '/cloud-service'
    | '/construction'
    | '/contact-us'
    | '/financial-services-and-fintech'
    | '/hybrid-cloud'
    | '/industries'
    | '/privacy'
    | '/products'
    | '/real-state'
    | '/retail-and-ecommerce'
    | '/services'
    | '/software-development'
    | '/solutions'
    | '/technology-and-high-growth-companies'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AutomationRoute: typeof AutomationRoute
  IntegrationAsAServiceRoute: typeof IntegrationAsAServiceRoute
  InternetOfThingRoute: typeof InternetOfThingRoute
  AboutUsLazyRoute: typeof AboutUsLazyRoute
  BusinessOutcomesLazyRoute: typeof BusinessOutcomesLazyRoute
  CloudServiceLazyRoute: typeof CloudServiceLazyRoute
  ConstructionLazyRoute: typeof ConstructionLazyRoute
  ContactUsLazyRoute: typeof ContactUsLazyRoute
  FinancialServicesAndFintechLazyRoute: typeof FinancialServicesAndFintechLazyRoute
  HybridCloudLazyRoute: typeof HybridCloudLazyRoute
  IndustriesLazyRoute: typeof IndustriesLazyRoute
  PrivacyLazyRoute: typeof PrivacyLazyRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
  RealStateLazyRoute: typeof RealStateLazyRoute
  RetailAndEcommerceLazyRoute: typeof RetailAndEcommerceLazyRoute
  ServicesLazyRoute: typeof ServicesLazyRoute
  SoftwareDevelopmentLazyRoute: typeof SoftwareDevelopmentLazyRoute
  SolutionsLazyRoute: typeof SolutionsLazyRoute
  TechnologyAndHighGrowthCompaniesLazyRoute: typeof TechnologyAndHighGrowthCompaniesLazyRoute
  TermsLazyRoute: typeof TermsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology-and-high-growth-companies': {
      id: '/technology-and-high-growth-companies'
      path: '/technology-and-high-growth-companies'
      fullPath: '/technology-and-high-growth-companies'
      preLoaderRoute: typeof TechnologyAndHighGrowthCompaniesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-development': {
      id: '/software-development'
      path: '/software-development'
      fullPath: '/software-development'
      preLoaderRoute: typeof SoftwareDevelopmentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail-and-ecommerce': {
      id: '/retail-and-ecommerce'
      path: '/retail-and-ecommerce'
      fullPath: '/retail-and-ecommerce'
      preLoaderRoute: typeof RetailAndEcommerceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-state': {
      id: '/real-state'
      path: '/real-state'
      fullPath: '/real-state'
      preLoaderRoute: typeof RealStateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hybrid-cloud': {
      id: '/hybrid-cloud'
      path: '/hybrid-cloud'
      fullPath: '/hybrid-cloud'
      preLoaderRoute: typeof HybridCloudLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-services-and-fintech': {
      id: '/financial-services-and-fintech'
      path: '/financial-services-and-fintech'
      fullPath: '/financial-services-and-fintech'
      preLoaderRoute: typeof FinancialServicesAndFintechLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-service': {
      id: '/cloud-service'
      path: '/cloud-service'
      fullPath: '/cloud-service'
      preLoaderRoute: typeof CloudServiceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-outcomes': {
      id: '/business-outcomes'
      path: '/business-outcomes'
      fullPath: '/business-outcomes'
      preLoaderRoute: typeof BusinessOutcomesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet-of-thing': {
      id: '/internet-of-thing'
      path: '/internet-of-thing'
      fullPath: '/internet-of-thing'
      preLoaderRoute: typeof InternetOfThingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-as-a-service': {
      id: '/integration-as-a-service'
      path: '/integration-as-a-service'
      fullPath: '/integration-as-a-service'
      preLoaderRoute: typeof IntegrationAsAServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AutomationRoute: AutomationRoute,
  IntegrationAsAServiceRoute: IntegrationAsAServiceRoute,
  InternetOfThingRoute: InternetOfThingRoute,
  AboutUsLazyRoute: AboutUsLazyRoute,
  BusinessOutcomesLazyRoute: BusinessOutcomesLazyRoute,
  CloudServiceLazyRoute: CloudServiceLazyRoute,
  ConstructionLazyRoute: ConstructionLazyRoute,
  ContactUsLazyRoute: ContactUsLazyRoute,
  FinancialServicesAndFintechLazyRoute: FinancialServicesAndFintechLazyRoute,
  HybridCloudLazyRoute: HybridCloudLazyRoute,
  IndustriesLazyRoute: IndustriesLazyRoute,
  PrivacyLazyRoute: PrivacyLazyRoute,
  ProductsLazyRoute: ProductsLazyRoute,
  RealStateLazyRoute: RealStateLazyRoute,
  RetailAndEcommerceLazyRoute: RetailAndEcommerceLazyRoute,
  ServicesLazyRoute: ServicesLazyRoute,
  SoftwareDevelopmentLazyRoute: SoftwareDevelopmentLazyRoute,
  SolutionsLazyRoute: SolutionsLazyRoute,
  TechnologyAndHighGrowthCompaniesLazyRoute:
    TechnologyAndHighGrowthCompaniesLazyRoute,
  TermsLazyRoute: TermsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
